return {
 [10001]={name="白银成就", des="累计获得150点成就点数后自动获得该称号", unlock_key=0, star=1, atlas="Achievement/AchievementTitle_Atlas.png", title_icon="cj1_bycj1", title_group=1, need_points=150, },
 [10002]={name="白银成就", des="累计获得250点成就点数后自动获得该称号", unlock_key=0, star=2, atlas="Achievement/AchievementTitle_Atlas.png", title_icon="cj1_bycj2", title_group=1, need_points=250, },
 [10003]={name="白银成就", des="累计获得400点成就点数后自动获得该称号", unlock_key=0, star=3, atlas="Achievement/AchievementTitle_Atlas.png", title_icon="cj1_bycj3", title_group=1, need_points=400, },
 [10004]={name="黄金成就", des="累计获得550点成就点数后自动获得该称号", unlock_key=0, star=1, atlas="Achievement/AchievementTitle_Atlas.png", title_icon="cj2_hjcj1", title_group=1, need_points=550, },
 [10005]={name="黄金成就", des="累计获得700点成就点数后自动获得该称号", unlock_key=0, star=2, atlas="Achievement/AchievementTitle_Atlas.png", title_icon="cj2_hjcj2", title_group=1, need_points=700, },
 [10006]={name="黄金成就", des="累计获得850点成就点数后自动获得该称号", unlock_key=0, star=3, atlas="Achievement/AchievementTitle_Atlas.png", title_icon="cj2_hjcj3", title_group=1, need_points=850, },
 [10007]={name="钻石成就", des="累计获得1000点成就点数后自动获得该称号", unlock_key=0, star=1, atlas="Achievement/AchievementTitle_Atlas.png", title_icon="cj3_zscj1", title_group=1, need_points=1000, },
 [10008]={name="钻石成就", des="累计获得1200点成就点数后自动获得该称号", unlock_key=0, star=2, atlas="Achievement/AchievementTitle_Atlas.png", title_icon="cj3_zscj2", title_group=1, need_points=1200, },
 [10009]={name="钻石成就", des="累计获得1400点成就点数后自动获得该称号", unlock_key=0, star=3, atlas="Achievement/AchievementTitle_Atlas.png", title_icon="cj3_zscj3", title_group=1, need_points=1400, },
 [10010]={name="超凡成就", des="累计获得1700点成就点数后自动获得该称号", unlock_key=0, star=1, atlas="Achievement/AchievementTitle_Atlas.png", title_icon="cj4_cfcj1", title_group=1, need_points=1700, },
 [10011]={name="超凡成就", des="累计获得2000点成就点数后自动获得该称号", unlock_key=0, star=2, atlas="Achievement/AchievementTitle_Atlas.png", title_icon="cj4_cfcj2", title_group=1, need_points=2000, },
 [10012]={name="超凡成就", des="累计获得2400点成就点数后自动获得该称号", unlock_key=0, star=3, atlas="Achievement/AchievementTitle_Atlas.png", title_icon="cj4_cfcj3", title_group=1, need_points=2400, },
 [10013]={name="王者成就", des="累计获得2800点成就点数后自动获得该称号", unlock_key=0, star=1, atlas="Achievement/AchievementTitle_Atlas.png", title_icon="cj5_wzcj1", title_group=1, need_points=2800, },
 [10014]={name="王者成就", des="累计获得3400点成就点数后自动获得该称号", unlock_key=0, star=2, atlas="Achievement/AchievementTitle_Atlas.png", title_icon="cj5_wzcj2", title_group=1, need_points=3400, },
 [10015]={name="王者成就", des="累计获得4000点成就点数后自动获得该称号", unlock_key=0, star=3, atlas="Achievement/AchievementTitle_Atlas.png", title_icon="cj5_wzcj3", title_group=1, need_points=4000, },
 [20001]={name="春意盎然", des="累计春天80次", unlock_key=0, star=-1, atlas="Achievement/AchievementTitle_Atlas.png", title_icon="ch_cyar", title_group=2, },
 [20002]={name="凛冬使者", des="累计反春80次", unlock_key=0, star=-1, atlas="Achievement/AchievementTitle_Atlas.png", title_icon="ch_ldsz", title_group=2, },
 [20003]={name="冬日拥抱者", des="累计被反春80次", unlock_key=0, star=-1, atlas="Achievement/AchievementTitle_Atlas.png", title_icon="ch_drybz", title_group=2, },
 [20004]={name="沾花惹草", des="累计使用互动表情500次", unlock_key=0, star=-1, atlas="Achievement/AchievementTitle_Atlas.png", title_icon="ch_zhrc", title_group=2, },
 [20005]={name="顺藤摸瓜", des="葫芦园收获金豆100次", unlock_key=0, star=-1, atlas="Achievement/AchievementTitle_Atlas.png", title_icon="ch_stmg", title_group=2, },
 [20006]={name="助人为乐", des="累计帮他人锄土500次", unlock_key=0, star=-1, atlas="Achievement/AchievementTitle_Atlas.png", title_icon="ch_zrwl", title_group=2, },
 [20011]={name="专业牌手", des="累计清空150个对手", unlock_key=0, star=-1, atlas="Achievement/AchievementTitle_Atlas.png", title_icon="ch_zyps", title_group=2, },
 [20012]={name="无情牌手", des="累计清空400个对手", unlock_key=0, star=-1, atlas="Achievement/AchievementTitle_Atlas.png", title_icon="ch_wqps", title_group=2, },
 [20013]={name="盆满钵满", des="累计赢豆超过2000亿", unlock_key=0, star=-1, atlas="Achievement/AchievementTitle_Atlas.png", title_icon="ch_pmbm", title_group=2, },
 [20014]={name="地主的压制", des="当地主获胜888次", unlock_key=0, star=-1, atlas="Achievement/AchievementTitle_Atlas.png", title_icon="ch_dzzyh", title_group=2, },
 [20015]={name="农民的反击", des="当农民获胜888次", unlock_key=0, star=-1, atlas="Achievement/AchievementTitle_Atlas.png", title_icon="ch_nmdfj", title_group=2, },
 [20016]={name="持续高压", des="斗地主中打出100000倍及以上88次", unlock_key=0, star=-1, atlas="Achievement/AchievementTitle_Atlas.png", title_icon="ch_cxgy", title_group=2, },
 [20017]={name="豆不care", des="单局输超过50亿", unlock_key=0, star=-1, atlas="Achievement/AchievementTitle_Atlas.png", title_icon="ch_dbc", title_group=2, },
 [20018]={name="壕不在意", des="单局输超过100亿", unlock_key=0, star=-1, atlas="Achievement/AchievementTitle_Atlas.png", title_icon="ch_hbzy", title_group=2, },
 [20019]={name="人生巅峰", des="单局赢超过50亿", unlock_key=0, star=-1, atlas="Achievement/AchievementTitle_Atlas.png", title_icon="ch_rsdf", title_group=2, },
 [20020]={name="还有谁？", des="单局赢超过100亿", unlock_key=0, star=-1, atlas="Achievement/AchievementTitle_Atlas.png", title_icon="ch_hys", title_group=2, },
 [30001]={name="好运起手", des="起手拿到4张癞子牌(七宝牌)", unlock_key=333, star=-1, atlas="Achievement/AchievementTitle_Atlas.png", title_icon="ch_hyqs", title_group=3, },
 [30002]={name="欧皇附体", des="一手牌拿到双王+4个2+4个A(斗地主)", unlock_key=0, star=-1, atlas="Achievement/AchievementTitle_Atlas.png", title_icon="ch_ohbh", title_group=3, },
 [30003]={name="近朱者赤", des="一手牌全是红色(斗地主)", unlock_key=0, star=-1, atlas="Achievement/AchievementTitle_Atlas.png", title_icon="ch_jzzc", title_group=3, },
 [30004]={name="近墨者黑", des="一手牌全是黑色(斗地主)", unlock_key=0, star=-1, atlas="Achievement/AchievementTitle_Atlas.png", title_icon="ch_jmzh", title_group=3, },
 [30005]={name="这就没了？", des="一手牌出完所有的手牌(斗地主)", unlock_key=0, star=-1, atlas="Achievement/AchievementTitle_Atlas.png", title_icon="ch_zjml", title_group=3, },
 [30006]={name="非酋附体", des="拿到一手牌最大手牌不超过9(斗地主)", unlock_key=0, star=-1, atlas="Achievement/AchievementTitle_Atlas.png", title_icon="ch_fqft", title_group=3, },
 [30007]={name="斗破仓穷", des="累计破产次数达到500次", unlock_key=0, star=-1, atlas="Achievement/AchievementTitle_Atlas.png", title_icon="ch_dpcq", title_group=3, },
 [30008]={name="连赢小王子", des="10连胜", unlock_key=0, star=-1, atlas="Achievement/AchievementTitle_Atlas.png", title_icon="ch_lyxwz", title_group=3, },
 [30009]={name="不信还能输", des="10连败", unlock_key=0, star=-1, atlas="Achievement/AchievementTitle_Atlas.png", title_icon="ch_bxhns", title_group=3, },
 [30010]={name="天胡王者", des="累计天胡88次(七宝牌)", unlock_key=333, star=-1, atlas="Achievement/AchievementTitle_Atlas.png", title_icon="ch_thwz", title_group=3, },
 [30011]={name="地胡王者", des="累计地胡100次(七宝牌)", unlock_key=333, star=-1, atlas="Achievement/AchievementTitle_Atlas.png", title_icon="ch_dhwz", title_group=3, },
 [30012]={name="八星归一", des="累计八星归一100次(七宝牌)", unlock_key=333, star=-1, atlas="Achievement/AchievementTitle_Atlas.png", title_icon="ch_bxgy", title_group=3, },
 [30013]={name="花满园", des="累计花满园88次(七宝牌)", unlock_key=333, star=-1, atlas="Achievement/AchievementTitle_Atlas.png", title_icon="ch_hmy", title_group=3, },
 [30014]={name="海底捞月", des="累计海底捞月66次(七宝牌)", unlock_key=333, star=-1, atlas="Achievement/AchievementTitle_Atlas.png", title_icon="ch_hdly", title_group=3, },
}