return {
 [50001]={rune_name="勋章印记", rune_type=1, rune_quality=5, rune_level_max=100, rune_basal_value={key="Medal",value=150}, rune_level_value=150, convert_exp=8000, atlas="Runes_Atlas.png", rune_icon="xzfw_1", rune_icon2="xzfw_1", rune_des="勋章加成", is_active=-1, },
 [50002]={rune_name="收礼印记", rune_type=2, rune_quality=5, rune_level_max=100, rune_basal_value={key="UserGiftVal",value=50}, rune_level_value=50, convert_exp=8000, atlas="Runes_Atlas.png", rune_icon="rqfw_1", rune_icon2="rqfw_1", rune_des="收礼人气加成", is_active=-1, },
 [50003]={rune_name="赢豆印记", rune_type=3, rune_quality=5, rune_level_max=100, rune_basal_value={key="GameWinGold",value=20}, rune_level_value=20, convert_exp=8000, atlas="Runes_Atlas.png", rune_icon="ydfw_1", rune_icon2="ydfw_1", rune_des="胜局时赢豆加成", is_active=1, },
 [50004]={rune_name="充豆印记", rune_type=4, rune_quality=5, rune_level_max=100, rune_basal_value={key="PayGold",value=30}, rune_level_value=30, convert_exp=8000, atlas="Runes_Atlas.png", rune_icon="dddfw_1", rune_icon2="dddfw_1", rune_des="充值买豆加成", is_active=1, },
 [50005]={rune_name="段位印记", rune_type=5, rune_quality=4, rune_level_max=100, rune_basal_value={key="GameWinExp",value=1090}, rune_level_value=90, convert_exp=4000, atlas="Runes_Atlas.png", rune_icon="jbfw_1", rune_icon2="jbfw_1", rune_des="段位荣誉加成", is_active=1, },
 [50006]={rune_name="仙露印记", rune_type=6, rune_quality=4, rune_level_max=100, rune_basal_value={key="GourdWaterDay",value=2280}, rune_level_value=280, convert_exp=4000, atlas="Runes_Atlas.png", rune_icon="sdfw_1", rune_icon2="sdfw_1", rune_des="葫芦园每天免费仙露加成", is_active=1, },
 [50007]={rune_name="丰收印记", rune_type=7, rune_quality=3, rune_level_max=100, rune_basal_value={key="GourdGoldBase",value=1090}, rune_level_value=90, convert_exp=4000, atlas="Runes_Atlas.png", rune_icon="zcfw_1", rune_icon2="zcfw_1", rune_des="葫芦园基础产量加成", is_active=1, },
 [50008]={rune_name="补助印记", rune_type=8, rune_quality=3, rune_level_max=100, rune_basal_value={key="BrokeGold",value=5550}, rune_level_value=550, convert_exp=2000, atlas="Runes_Atlas.png", rune_icon="bzfw", rune_icon2="bzfw", rune_des="破产补助金豆加成", is_active=1, },
 [50009]={rune_name="签到印记", rune_type=9, rune_quality=3, rune_level_max=100, rune_basal_value={key="SignInGold",value=5550}, rune_level_value=550, convert_exp=2000, atlas="Runes_Atlas.png", rune_icon="dkfw_1", rune_icon2="dkfw_1", rune_des="签到领取金豆加成", is_active=1, },
 [50010]={rune_name="息壤印记", rune_type=10, rune_quality=4, rune_level_max=100, rune_basal_value={key="XirangAd",value=2280}, rune_level_value=280, convert_exp=2000, atlas="Runes_Atlas.png", rune_icon="xryj_1", rune_icon2="xryj_1", rune_des="葫芦园每天免费息壤加成", is_active=1, },
}