return {
 [1]={effect_name="deal_card", game_id=3, delay_time=5500, des="七雀牌发牌（包含发牌、理牌、首出动效的时间）", },
 [2]={effect_name="take_card", game_id=3, delay_time=130, des="七雀牌抽牌", },
 [3]={effect_name="take_card_flower", game_id=3, delay_time=1000, des="七雀牌抽到花牌", },
 [4]={effect_name="play_card", game_id=3, delay_time=600, des="七雀牌打牌", },
 [5]={effect_name="hu", game_id=3, delay_time=0, des="effect_code表的hu（可以看做是普通打出牌的时间） + effect表的牌型时间（包括普通胡和各种特殊牌型） + effect表的事件时间（自摸，天胡，地胡，海底捞月，清一色）", },
 [100]={effect_name="DealCardWaite", game_id=1, delay_time=5000, des="斗地主发牌延时", },
 [101]={effect_name="SetLandlordWaite", game_id=1, delay_time=1000, des="斗地主确认地主延时", },
 [102]={effect_name="DoubleingWaite", game_id=1, delay_time=1000, des="斗地主加倍延时", },
 [103]={effect_name="DoubleMaxWaite", game_id=1, delay_time=1000, des="斗地主封顶翻倍延时", },
 [400]={effect_name="DealCardWaite", game_id=4, delay_time=5000, des="斗地主扑克牌发牌延时", },
 [401]={effect_name="DealCardAceWaite", game_id=4, delay_time=2500, des="斗地主锦囊牌发牌延时", },
 [402]={effect_name="SetLandlordWaite", game_id=4, delay_time=1000, des="斗地主确认地主延时", },
 [403]={effect_name="DoubleingWaite", game_id=4, delay_time=1000, des="斗地主加倍延时", },
 [404]={effect_name="DoubleMaxWaite", game_id=4, delay_time=1000, des="斗地主封顶翻倍延时", },
}