return {
 [1]={fashion_id=195001, scene=1, card_type_suffix="", bg_route="Textures/UIBg/", bg_name="djbg_1", bg_effects_route="Prefabs/UIBg/UIBgEffect/", bg_effects_name="effect_ui_bg_chuan", },
 [2]={fashion_id=195001, scene=3, card_type_suffix="", bg_route="Textures/UIBg/", bg_name="djbg_3", bg_effects_route="", bg_effects_name="", },
 [3]={fashion_id=195001, scene=4, card_type_suffix="", bg_route="Textures/UIBg/", bg_name="djbg_2", bg_effects_route="", bg_effects_name="", },
 [4]={fashion_id=195002, scene=1, card_type_suffix="", bg_route="Textures/UIBg/", bg_name="cjbg_1", bg_effects_route="", bg_effects_name="", },
 [5]={fashion_id=195002, scene=3, card_type_suffix="", bg_route="Textures/UIBg/", bg_name="cjbg_1", bg_effects_route="", bg_effects_name="", },
 [6]={fashion_id=195002, scene=4, card_type_suffix="", bg_route="Textures/UIBg/", bg_name="cjbg_1", bg_effects_route="", bg_effects_name="", },
 [7]={fashion_id=200001, scene=1, card_type_suffix="", bg_route="Textures/UIDesk/", bg_name="zz_tp", bg_effects_route="", bg_effects_name="", },
 [8]={fashion_id=200001, scene=3, card_type_suffix="", bg_route="Textures/UIDesk/", bg_name="zz_tp3", bg_effects_route="", bg_effects_name="", },
 [9]={fashion_id=200001, scene=4, card_type_suffix="", bg_route="Textures/UIDesk/", bg_name="zz_tp7", bg_effects_route="", bg_effects_name="", },
 [10]={fashion_id=200002, scene=1, card_type_suffix="", bg_route="Textures/UIDesk/", bg_name="zz_tp8", bg_effects_route="", bg_effects_name="", },
 [11]={fashion_id=200002, scene=3, card_type_suffix="", bg_route="Textures/UIDesk/", bg_name="zz_tp8", bg_effects_route="", bg_effects_name="", },
 [12]={fashion_id=200002, scene=4, card_type_suffix="", bg_route="Textures/UIDesk/", bg_name="zz_tp8", bg_effects_route="", bg_effects_name="", },
 [13]={fashion_id=215001, scene=1, card_type_suffix="", bg_route="", bg_name="", bg_effects_route="", bg_effects_name="", },
 [14]={fashion_id=215001, scene=3, card_type_suffix="", bg_route="", bg_name="", bg_effects_route="", bg_effects_name="", },
 [15]={fashion_id=215001, scene=4, card_type_suffix="", bg_route="", bg_name="", bg_effects_route="", bg_effects_name="", },
 [16]={fashion_id=215002, scene=1, card_type_suffix="xc", bg_route="", bg_name="", bg_effects_route="", bg_effects_name="", },
 [17]={fashion_id=215002, scene=3, card_type_suffix="xc", bg_route="", bg_name="", bg_effects_route="", bg_effects_name="", },
 [18]={fashion_id=215002, scene=4, card_type_suffix="xc", bg_route="", bg_name="", bg_effects_route="", bg_effects_name="", },
}