return {
 [1001]={scene="CalabashVine", sceneClassName="CalabashMain", ui="", page="", func="SetJunmpIndex", args={index=1}, can_jump_battle=0, back=nil, des="葫芦藤主界面", },
 [1002]={scene="CalabashVine", sceneClassName="CalabashMain", ui="", page="", func="SetJunmpIndex", args={index=2}, can_jump_battle=0, back=nil, des="葫芦藤-摘豆", },
 [1003]={scene="CalabashVine", sceneClassName="CalabashMain", ui="", page="", func="SetJunmpIndex", args={index=3}, can_jump_battle=0, back=nil, des="葫芦藤主界面-并浇水一次", },
 [1004]={scene="CalabashVine", sceneClassName="CalabashMain", ui="", page="", func="SetJunmpIndex", args={index=4}, can_jump_battle=0, back=nil, des="葫芦藤主界面-并施肥一次", },
 [1005]={scene="CalabashVine", sceneClassName="CalabashMain", ui="", page="", func="SetJunmpIndex", args={index=5}, can_jump_battle=0, back=nil, des="葫芦藤主界面-并收获金豆一次", },
 [2001]={scene="RoleDevelopment", sceneClassName="RoleDeveMain", ui="", page="", func="SetJumpDes", args={roleId=0,page=1}, can_jump_battle=0, back=nil, des="角色-技能页", },
 [2002]={scene="RoleDevelopment", sceneClassName="RoleDeveMain", ui="", page="", func="SetJumpDes", args={roleId=0,page=2}, can_jump_battle=0, back=nil, des="角色-符文页", },
 [2003]={scene="RoleDevelopment", sceneClassName="RoleDeveMain", ui="", page="", func="SetJumpDes", args={roleId=0,page=3}, can_jump_battle=0, back=nil, des="角色-心情页", },
 [2004]={scene="RoleDevelopment", sceneClassName="RoleDeveMain", ui="", page="", func="SetJumpOtherPanel", args={name="RuneManagePanel",page=1}, can_jump_battle=0, back=nil, des="角色-符文-符文详情-未获得,0是默认第1个，1是第2个，类推", },
 [4001]={scene="DaTing2", sceneClassName="", ui="Ranking/UIRankingList", page="", func="OnJump", args={page=1,type=3}, can_jump_battle=0, back=nil, des="排行榜-人气-月榜", },
 [5001]={scene="DaTing2", sceneClassName="", ui="", page="", func="GameQuickStart", args=nil, can_jump_battle=0, back=nil, des="相当于发送了主界面的快速开始按钮", },
 [5002]={scene="DaTing2", sceneClassName="", ui="", page="", func="GameQuickStart", args={gameid = 1}, can_jump_battle=0, back=nil, des="相当于发送了一次不洗牌选房界面的快速开始", },
 [5003]={scene="DaTing2", sceneClassName="", ui="", page="", func="GameQuickStart", args={gameid = 3}, can_jump_battle=0, back=nil, des="相当于发送了一次七雀牌选房界面的快速开始", },
 [6001]={scene="DaTing2", sceneClassName="", ui="Shop/ShopUI", page="", func="", args=nil, can_jump_battle=0, back=nil, des="猫盒界面", },
 [7001]={scene="DaTing2", sceneClassName="", ui="Shop/ShopUI", page="", func="", args=nil, can_jump_battle=0, back=nil, des="商城-金豆-特价金豆", },
 [8001]={scene="DaTing2", sceneClassName="", ui="Achievement/UIAchievementPanel", page="", func="OnOpenChoose", args=nil, can_jump_battle=0, back=nil, des="打开成就主界面", },
 [9001]={scene="", sceneClassName="", ui="礼包界面名", page="", func="", args=nil, can_jump_battle=1, back=true, des="显示限时礼包弹框", },
 [10001]={scene="", sceneClassName="", ui="RoomSelect/UIRoomSelect", page="", func="PlayQQPGuideFromHelp", args=nil, can_jump_battle=0, back=nil, des="七雀牌图文引导", },
}