return {
 c2s ={
c2s_handshake = "c2s_handshake" ,--  101 
c2s_get = "c2s_get" ,--  102 
c2s_set = "c2s_set" ,--  103 
c2s_quit = "c2s_quit" ,--  104 
get_game_record = "get_game_record" ,--  105 
heartbeat = "heartbeat" ,--  1 
c2s_servertime = "c2s_servertime" ,--  2 
logout = "logout" ,--  3 
GetUserInfo = "GetUserInfo" ,--  4 
GetUserItemDatas = "GetUserItemDatas" ,--  5 
UseItem = "UseItem" ,--  6 
SetNickName = "SetNickName" ,--  600 
SetGender = "SetGender" ,--  601 
SetHead = "SetHead" ,--  602 
SetSignature = "SetSignature" ,--  603 
SetHeadFrame = "SetHeadFrame" ,--  604 
SetChatFrame = "SetChatFrame" ,--  605 
UserLike = "UserLike" ,--  606 
UserCmd = "UserCmd" ,--  610 
GetLvReward = "GetLvReward" ,--  615 
GetGameRecordArr = "GetGameRecordArr" ,--  616 
GetUserMailDatas = "GetUserMailDatas" ,--  630 
ReadMail = "ReadMail" ,--  631 
GetMailItem = "GetMailItem" ,--  632 
RemoveMail = "RemoveMail" ,--  633 
GetUserTaskDatas = "GetUserTaskDatas" ,--  650 
GetTaskItem = "GetTaskItem" ,--  651 
GetUserHeroDatas = "GetUserHeroDatas" ,--  670 
HeroSkillLvUp = "HeroSkillLvUp" ,--  671 
HeroMoodUp = "HeroMoodUp" ,--  672 
HeroUse = "HeroUse" ,--  673
GetUserRuneDatas = "GetUserRuneDatas",
RuneEquip = "RuneEquip", -- 691
RuneUnEquip = "RuneUnEquip", -- 692
RuneLvUp = "RuneLvUp",
GetUserStoreDatas = "GetUserStoreDatas",--740
StoreBuy = "StoreBuy", -- 741
PieceShop_TakePiece = "PieceShop_TakePiece",
GetGourdData = "GetGourdData", --770
GourdGetWaterReward = "GourdGetWaterReward", -- 772
GourdFixedTimeReward = "GourdFixedTimeReward",
GourdFertilizer = "GourdFertilizer", -- 774
GourdFriendHelpApply = "GourdFriendHelpApply", -- 774
GourdFriendHelp = "GourdFriendHelp",--778
GourdLoosenSoil = "GourdLoosenSoil",
GourdActionRecordGet = "GourdActionRecordGet",
GourdCollectUser = "GourdCollectUser",
GourdPickFruit = "GourdPickFruit",
GourdPickFruitQuick = "GourdPickFruitQuick",
GourdWatering = "GourdWatering",
GourdPickFruit = "GourdPickFruit",
GourdPickFruitQuick = "GourdPickFruitQuick",
GourdCollectUser = "GourdCollectUser",
GourdLoosenSoilBoxOpen = "GourdLoosenSoilBoxOpen",
base_info = "base_info" ,--  1000 
horselamps = "horselamps" ,--  1001 
receive_title_season_reward = "receive_title_season_reward" ,--  1003 
realname_auth = "realname_auth" ,--  1004 
backpack = "backpack" ,--  1005 
give_advice = "give_advice" ,--  1006 
redpoint = "redpoint" ,--  1007 
gain_verify_code = "gain_verify_code" ,--  1008 
exchange_cdk = "exchange_cdk" ,--  1009 
start_match = "start_match" ,--  1100 
cancel_match = "cancel_match" ,--  1101 
game_records = "game_records" ,--  1102 
game_record_content = "game_record_content" ,--  1103 
buy = "buy" ,--  1200 
ali_order = "ali_order" ,--  1201 
wx_order = "wx_order" ,--  1202 
huawei_order = "huawei_order" ,--  1203 
huawei_pay_suc = "huawei_pay_suc" ,--  1204 
query_mails = "query_mails" ,--  1300 
read_mail = "read_mail" ,--  1301 
receive_mail = "receive_mail" ,--  1302 
delete_mail = "delete_mail" ,--  1303 
receive_dailytask_reward = "receive_dailytask_reward" ,--  1360 
receive_dailytask_activity_reward = "receive_dailytask_activity_reward" ,--  1361 
bank_info = "bank_info" ,--  1400 
bank_deposit = "bank_deposit" ,--  1401 
bank_takeout = "bank_takeout" ,--  1402 
bank_upgrade = "bank_upgrade" ,--  1403 
bank_upgrade_oneclick = "bank_upgrade_oneclick" ,--  1404 
active_info = "active_info" ,--  1500 
sub_active = "sub_active" ,--  1501 
unsub_active = "unsub_active" ,--  1502 
sign = "sign" ,--  1503 
receive_consume_reward = "receive_consume_reward" ,--  1504 
dailyshare = "dailyshare" ,--  1505 
receive_online_gift = "receive_online_gift" ,--  1506 
receive_winning_streak = "receive_winning_streak" ,--  1507 
receive_totalcharge = "receive_totalcharge" ,--  1508 
receive_singlecharge = "receive_singlecharge" ,--  1509 
receive_group_buy = "receive_group_buy" ,--  1510 
receive_monthcard = "receive_monthcard" ,--  1511 
receive_relieffund = "receive_relieffund" ,--  1512 
receive_invite_newplayer = "receive_invite_newplayer" ,--  1513 
join_invite_newplayer = "join_invite_newplayer" ,--  1514 
me_invite_newplayer = "me_invite_newplayer" ,--  1515 
invite_info = "invite_info" ,--  1516 
ok_invite = "ok_invite" ,--  1517 
receive_yearcard = "receive_yearcard" ,--  1518 
room_info = "room_info" ,--  2000 
card_recorder = "card_recorder" ,--  2001 
trusteeship = "trusteeship" ,--  2002 
cancel_trusteeship = "cancel_trusteeship" ,--  2003 
showcard = "showcard" ,--  2004 
call_landlord = "call_landlord" ,--  2005 
rob_landlord = "rob_landlord" ,--  2006 
overlord_rob_landlord = "overlord_rob_landlord" ,--  2007 
double = "double" ,--  2008 
double_cap = "double_cap" ,--  2009 
playcard = "playcard" ,--  2010 
check_bottom_card = "check_bottom_card" ,--  2011 
game_report = "game_report" ,--  2100 
GameChat = "GameChat" ,--  2101 
unleash_magic = "unleash_magic" ,--  2102 
mute = "mute" ,--  2103 
ssw_room_info = "ssw_room_info" ,--  2200 
ssw_takecard = "ssw_takecard" ,--  2201 
ssw_playcard = "ssw_playcard" ,--  2202 
ssw_hu = "ssw_hu" ,--  2203 
ssw_giveup = "ssw_giveup" ,--  2204 
ssw_exit = "ssw_exit" ,--  2205 
ssw_card_recorder = "ssw_card_recorder" ,--  2206 
ssw_complete_guide = "ssw_complete_guide" ,--  2207 
ssw_praise = "ssw_praise" ,--  2208
PieceShop_BuyGoods = "PieceShop_BuyGoods", -- 4007
GetUserHeroDatasExt = "GetUserHeroDatasExt", -- 4030
PieceShop_GetInfo = "PieceShop_GetInfo",
},



 s2c ={
  s2c_heartbeat = "s2c_heartbeat" ,--  1 
  MailTip = "MailTip" ,--  630
  SyncUserItem = "SyncUserItem",
  SyncUserHero = "SyncUserHero",
  SyncUserStore = "SyncUserStore",
  sync_gold = "sync_gold" ,--  1000 
  sync_diamond = "sync_diamond" ,--  1001 
  sync_coupon = "sync_coupon" ,--  1002 
  sync_backpack = "sync_backpack" ,--  1003 
  sync_dailytask = "sync_dailytask" ,--  1004 
  sync_redpoint = "sync_redpoint" ,--  1005 
  sync_count = "sync_count" ,--  1006 
  sync_vip = "sync_vip" ,--  1007 
  immediate_horselamp = "immediate_horselamp" ,--  1008 
  sync_bank = "sync_bank" ,--  1009 
  match_ok = "match_ok" ,--  1100 
  buy_suc = "buy_suc" ,--  1200 
  sync_active_info = "sync_active_info" ,--  1500 
  sync_active_conf = "sync_active_conf" ,--  1501 
  invite = "invite" ,--  1502 
  ok_invite = "ok_invite" ,--  1503 
  game_start_dealcard = "game_start_dealcard" ,--  2000 
  determine_landlord = "determine_landlord" ,--  2001 
  gameover = "gameover" ,--  2002 
  p_trusteeship = "p_trusteeship" ,--  2003 
  p_cancel_trusteeship = "p_cancel_trusteeship" ,--  2004 
  p_showcard = "p_showcard" ,--  2005 
  p_call_landlord = "p_call_landlord" ,--  2006 
  p_rob_landlord = "p_rob_landlord" ,--  2007 
  p_overlord_rob_landlord = "p_overlord_rob_landlord" ,--  2008 
  p_double = "p_double" ,--  2009 
  p_double_cap = "p_double_cap" ,--  2010 
  p_playcard = "p_playcard" ,--  2011 
  please_call_landlord = "please_call_landlord" ,--  2012 
  please_rob_landlord = "please_rob_landlord" ,--  2013 
  please_overlord_rob_landlord = "please_overlord_rob_landlord" ,--  2014 
  please_double = "please_double" ,--  2015 
  please_double_cap = "please_double_cap" ,--  2016 
  please_playcard = "please_playcard" ,--  2017 
  sync_multiple = "sync_multiple" ,--  2018 
  deduction_room_ticket = "deduction_room_ticket" ,--  2019 
  sync_player_gold = "sync_player_gold" ,--  2020 
  PlayerGameChat = "PlayerGameChat" ,--  2100 
  p_unleash_magic = "p_unleash_magic" ,--  2101 
  p_mute = "p_mute" ,--  2102 
  ssw_match_ok = "ssw_match_ok" ,--  2200 
  ssw_gamestart = "ssw_gamestart" ,--  2201 
  ssw_gameover = "ssw_gameover" ,--  2202 
  ssw_p_swapcard = "ssw_p_swapcard" ,--  2203 
  ssw_p_takecard = "ssw_p_takecard" ,--  2204 
  ssw_p_playcard = "ssw_p_playcard" ,--  2205 
  ssw_p_hu = "ssw_p_hu" ,--  2206 
  ssw_p_giveup = "ssw_p_giveup" ,--  2207 
  ssw_p_exit = "ssw_p_exit" ,--  2208 
  ssw_p_praise = "ssw_p_praise" ,--  2210 
  ssw_please_takecard = "ssw_please_takecard" ,--  2209
 }

}